services:
  postgres-db:
    container_name: todo-db
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: todo_dev
      POSTGRES_PASSWORD: todo_dev12
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
